theme: jekyll-theme-minimal
title: TIAN XIAO
description: National University of Singapore<br><br>I am an undergraduate sophomore from National University of Singapore (NUS) studying applied mathematics and computer science double degree. I am particularly interested in applying mathematical theories onto computing, such as machine learning, computational theory, etc. This website I made here consists of three parts - my portfolio, my research projects as well as my academic resources. Welcome to my website! 
logo: /img/logo.png
classes: wide
site_favicon: favicon.png
