theme: jekyll-theme-minimal

title: TIAN XIAO

author: Snoide Tian Xiao

navbar-links:
  resources: "https://github.com/snoidetx/snoidetx.github.io/tree/resources"
 
avatar: "/img/logo.jpg"
round-avatar: false
